from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies: list[tuple[str, str]] = []

    operations = [
        migrations.RunSQL(
            sql=[
                """
                CREATE TABLE IF NOT EXISTS sec_user (
                  usr_id varchar(8) PRIMARY KEY,
                  usr_fname varchar(20) NOT NULL,
                  usr_lname varchar(20) NOT NULL,
                  usr_pwd varchar(128) NOT NULL,
                  usr_type varchar(1) NOT NULL
                )
                """,
                """
                CREATE TABLE IF NOT EXISTS customer (
                  cust_id numeric(9,0) PRIMARY KEY,
                  cust_first_name varchar(25) NOT NULL,
                  cust_middle_name varchar(25) NOT NULL,
                  cust_last_name varchar(25) NOT NULL,
                  cust_addr_line_1 varchar(50) NOT NULL,
                  cust_addr_line_2 varchar(50) NOT NULL,
                  cust_addr_line_3 varchar(50) NOT NULL,
                  cust_addr_state_cd varchar(2) NOT NULL,
                  cust_addr_country_cd varchar(3) NOT NULL,
                  cust_addr_zip varchar(10) NOT NULL,
                  cust_phone_num_1 varchar(15) NOT NULL,
                  cust_phone_num_2 varchar(15) NOT NULL,
                  cust_ssn numeric(9,0) NOT NULL,
                  cust_govt_issued_id varchar(20) NOT NULL,
                  cust_dob_yyyy_mm_dd varchar(10) NOT NULL,
                  cust_eft_account_id varchar(10) NOT NULL,
                  cust_pri_card_holder_ind varchar(1) NOT NULL,
                  cust_fico_credit_score numeric(3,0) NOT NULL
                )
                """,
                """
                CREATE TABLE IF NOT EXISTS account (
                  acct_id numeric(11,0) PRIMARY KEY,
                  acct_active_status varchar(1) NOT NULL,
                  acct_curr_bal numeric(12,2) NOT NULL,
                  acct_credit_limit numeric(12,2) NOT NULL,
                  acct_cash_credit_limit numeric(12,2) NOT NULL,
                  acct_open_date varchar(10) NOT NULL,
                  acct_expiraion_date varchar(10) NOT NULL,
                  acct_reissue_date varchar(10) NOT NULL,
                  acct_curr_cyc_credit numeric(12,2) NOT NULL,
                  acct_curr_cyc_debit numeric(12,2) NOT NULL,
                  acct_addr_zip varchar(10) NOT NULL,
                  acct_group_id varchar(10) NOT NULL
                )
                """,
                """
                CREATE TABLE IF NOT EXISTS card (
                  card_num varchar(16) PRIMARY KEY,
                  card_acct_id numeric(11,0) NOT NULL,
                  card_cvv_cd numeric(3,0) NOT NULL,
                  card_embossed_name varchar(50) NOT NULL,
                  card_expiraion_date varchar(10) NOT NULL,
                  card_active_status varchar(1) NOT NULL
                )
                """,
                "CREATE INDEX IF NOT EXISTS card_acct_id_idx ON card (card_acct_id)",
                """
                CREATE TABLE IF NOT EXISTS card_xref (
                  xref_card_num varchar(16) PRIMARY KEY,
                  xref_cust_id numeric(9,0) NOT NULL,
                  xref_acct_id numeric(11,0) NOT NULL
                )
                """,
                "CREATE INDEX IF NOT EXISTS card_xref_cust_idx ON card_xref (xref_cust_id)",
                "CREATE INDEX IF NOT EXISTS card_xref_acct_idx ON card_xref (xref_acct_id)",
                """
                CREATE TABLE IF NOT EXISTS transaction_type (
                  tr_type varchar(2) PRIMARY KEY,
                  tr_description varchar(50) NOT NULL
                )
                """,
                """
                CREATE TABLE IF NOT EXISTS transaction_category (
                  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  tr_type varchar(2) NOT NULL,
                  tr_cat_cd varchar(4) NOT NULL,
                  tr_cat_type_desc varchar(50) NOT NULL,
                  CONSTRAINT transaction_category_pk UNIQUE (tr_type, tr_cat_cd)
                )
                """,
                """
                CREATE TABLE IF NOT EXISTS tran_cat_balance (
                  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  acct_id numeric(11,0) NOT NULL,
                  type_cd varchar(2) NOT NULL,
                  cat_cd varchar(4) NOT NULL,
                  tran_cat_bal numeric(11,2) NOT NULL,
                  CONSTRAINT tran_cat_balance_pk UNIQUE (acct_id, type_cd, cat_cd)
                )
                """,
                """
                CREATE TABLE IF NOT EXISTS disclosure_group (
                  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  acct_group_id varchar(10) NOT NULL,
                  tran_type_cd varchar(2) NOT NULL,
                  tran_cat_cd varchar(4) NOT NULL,
                  int_rate numeric(6,2) NOT NULL,
                  CONSTRAINT disclosure_group_pk UNIQUE (acct_group_id, tran_type_cd, tran_cat_cd)
                )
                """,
                """
                CREATE TABLE IF NOT EXISTS "transaction" (
                  tran_id varchar(16) PRIMARY KEY,
                  type_cd varchar(2) NOT NULL,
                  cat_cd varchar(4) NOT NULL,
                  source varchar(10) NOT NULL,
                  "desc" varchar(100) NOT NULL,
                  amt numeric(11,2) NOT NULL,
                  merchant_id numeric(9,0) NOT NULL,
                  merchant_name varchar(50) NOT NULL,
                  merchant_city varchar(50) NOT NULL,
                  merchant_zip varchar(10) NOT NULL,
                  card_num varchar(16) NOT NULL,
                  orig_ts varchar(26) NOT NULL,
                  proc_ts varchar(26) NOT NULL
                )
                """,
                "CREATE INDEX IF NOT EXISTS transaction_card_num_idx ON \"transaction\" (card_num)",
                """
                CREATE TABLE IF NOT EXISTS daily_transaction (
                  dalytran_id varchar(16) PRIMARY KEY,
                  type_cd varchar(2) NOT NULL,
                  cat_cd varchar(4) NOT NULL,
                  source varchar(10) NOT NULL,
                  "desc" varchar(100) NOT NULL,
                  amt numeric(11,2) NOT NULL,
                  merchant_id numeric(9,0) NOT NULL,
                  merchant_name varchar(50) NOT NULL,
                  merchant_city varchar(50) NOT NULL,
                  merchant_zip varchar(10) NOT NULL,
                  card_num varchar(16) NOT NULL,
                  orig_ts varchar(26) NOT NULL,
                  proc_ts varchar(26) NOT NULL
                )
                """,
                """
                CREATE TABLE IF NOT EXISTS daily_rejects (
                  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  dalytran_id varchar(16) NOT NULL,
                  reason varchar(80) NOT NULL,
                  card_num varchar(16) NOT NULL,
                  raw_payload text NOT NULL DEFAULT '',
                  created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """,
                """
                CREATE TABLE IF NOT EXISTS pending_auth_summary (
                  card_num varchar(16) PRIMARY KEY,
                  acct_id numeric(11,0) NOT NULL,
                  cust_id numeric(9,0) NOT NULL,
                  auth_status varchar(1) NOT NULL DEFAULT 'P',
                  account_status varchar(10) NOT NULL DEFAULT '',
                  credit_limit numeric(11,2) NOT NULL,
                  cash_limit numeric(11,2) NOT NULL,
                  credit_balance numeric(11,2) NOT NULL,
                  cash_balance numeric(11,2) NOT NULL,
                  approved_auth_cnt integer NOT NULL DEFAULT 0,
                  declined_auth_cnt integer NOT NULL DEFAULT 0,
                  approved_auth_amt numeric(11,2) NOT NULL DEFAULT 0,
                  declined_auth_amt numeric(11,2) NOT NULL DEFAULT 0
                )
                """,
                """
                CREATE TABLE IF NOT EXISTS pending_auth_detail (
                  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  auth_date varchar(6) NOT NULL,
                  auth_time varchar(6) NOT NULL,
                  auth_orig_date varchar(6) NOT NULL,
                  auth_orig_time varchar(6) NOT NULL,
                  card_num varchar(16) NOT NULL,
                  auth_type varchar(4) NOT NULL,
                  card_expiry_date varchar(4) NOT NULL,
                  message_type varchar(6) NOT NULL,
                  message_source varchar(6) NOT NULL,
                  auth_id_code varchar(6) NOT NULL,
                  auth_resp_code varchar(2) NOT NULL,
                  auth_resp_reason varchar(4) NOT NULL,
                  processing_code varchar(6) NOT NULL,
                  transaction_amt numeric(12,2) NOT NULL,
                  approved_amt numeric(12,2) NOT NULL,
                  merchant_catagory_code varchar(4) NOT NULL,
                  acqr_country_code varchar(3) NOT NULL,
                  pos_entry_mode integer NOT NULL,
                  merchant_id varchar(15) NOT NULL,
                  merchant_name varchar(22) NOT NULL,
                  merchant_city varchar(13) NOT NULL,
                  merchant_state varchar(2) NOT NULL,
                  merchant_zip varchar(9) NOT NULL,
                  transaction_id varchar(15) NOT NULL,
                  match_status varchar(1) NOT NULL DEFAULT 'P',
                  auth_fraud varchar(1) NOT NULL DEFAULT '',
                  fraud_rpt_date varchar(8) NOT NULL DEFAULT '',
                  CONSTRAINT pending_auth_detail_pk UNIQUE (auth_date, auth_time)
                )
                """,
                """
                CREATE TABLE IF NOT EXISTS auth_fraud (
                  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  card_num varchar(16) NOT NULL,
                  auth_ts timestamp with time zone NOT NULL,
                  auth_type varchar(4) NOT NULL DEFAULT '',
                  card_expiry_date varchar(4) NOT NULL DEFAULT '',
                  message_type varchar(6) NOT NULL DEFAULT '',
                  message_source varchar(6) NOT NULL DEFAULT '',
                  auth_id_code varchar(6) NOT NULL DEFAULT '',
                  auth_resp_code varchar(2) NOT NULL DEFAULT '',
                  auth_resp_reason varchar(4) NOT NULL DEFAULT '',
                  processing_code varchar(6) NOT NULL DEFAULT '',
                  transaction_amt numeric(12,2) NOT NULL DEFAULT 0,
                  approved_amt numeric(12,2) NOT NULL DEFAULT 0,
                  merchant_catagory_code varchar(4) NOT NULL DEFAULT '',
                  acqr_country_code varchar(3) NOT NULL DEFAULT '',
                  pos_entry_mode integer NOT NULL DEFAULT 0,
                  merchant_id varchar(15) NOT NULL DEFAULT '',
                  merchant_name varchar(22) NOT NULL DEFAULT '',
                  merchant_city varchar(13) NOT NULL DEFAULT '',
                  merchant_state varchar(2) NOT NULL DEFAULT '',
                  merchant_zip varchar(9) NOT NULL DEFAULT '',
                  transaction_id varchar(15) NOT NULL DEFAULT '',
                  match_status varchar(1) NOT NULL DEFAULT '',
                  auth_fraud varchar(1) NOT NULL DEFAULT '',
                  fraud_rpt_date date NULL,
                  acct_id numeric(11,0) NULL,
                  cust_id numeric(9,0) NULL,
                  CONSTRAINT auth_fraud_pk UNIQUE (card_num, auth_ts)
                )
                """,
            ],
            reverse_sql=[
                'DROP TABLE IF EXISTS auth_fraud',
                'DROP TABLE IF EXISTS pending_auth_detail',
                'DROP TABLE IF EXISTS pending_auth_summary',
                'DROP TABLE IF EXISTS daily_rejects',
                'DROP TABLE IF EXISTS daily_transaction',
                'DROP TABLE IF EXISTS "transaction"',
                'DROP TABLE IF EXISTS disclosure_group',
                'DROP TABLE IF EXISTS tran_cat_balance',
                'DROP TABLE IF EXISTS transaction_category',
                'DROP TABLE IF EXISTS transaction_type',
                'DROP TABLE IF EXISTS card_xref',
                'DROP TABLE IF EXISTS card',
                'DROP TABLE IF EXISTS account',
                'DROP TABLE IF EXISTS customer',
                'DROP TABLE IF EXISTS sec_user',
            ],
        )
    ]
